In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
df.shape

(50000, 2)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(49582, 2)

## Pre-processing

### 1. Converting to Lowercase

In [8]:
df["review"] = df["review"].str.lower()

### 2. Removing URLs

In [9]:
import re

# sample_text = "abc is the word, abc"
# new_text = re.sub("abc", "xyz", sample_text)
# print(new_text)

In [10]:
def remove_urls(text):
    text = re.sub(r"http\S+", "", text) #pattern , replicate, string 
    return text

df["review"] = df["review"].apply(remove_urls)

### 3. Removing punctuations

In [11]:
def remove_punctuations(text):
    text = re.sub(r"^A-Za-z0-9\S", "", text) 
    return text

df["review"] = df["review"].apply(remove_punctuations)

### 4. Removing the HTML

In [12]:
def remove_html(text):
    text = re.sub(r"<.*?>", "", text) 
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Removing the Stopwords

In [13]:
import nltk 
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [15]:
# sample_text = "I like coding in python"
# tokens = word_tokenize(sample_text)

In [16]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [17]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode 'll  h...  positive
1   wderful ltle producti.  filming technique   u...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly 's  fmly   lttle boy (jke) thks 's  zom...  negative
4  petter mttei's "love   time  mey"   vully stun...  positive

### 6. Stemming

In [18]:
#running => run, coding => code, wonderful => wonder
from nltk.stem import PorterStemmer

In [19]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

### 7. Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [21]:
y = df["sentiment"]

In [22]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [23]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod 'll hook . y rght...          1
1  wder ltle producti . film techniqu unssuming- ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli 's fmli lttle boy ( jke ) thk 's zomb c...          0
4  petter mttei 's `` love time mey '' vulli stun...          1

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000) #imp to add this max feature otherwise data will become too large

X = tf.fit_transform(df["review"])

In [26]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4093266 stored elements and shape (49582, 5000)>

In [27]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4093266 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3547)	0.05259795121393043
  (0, 2875)	0.08918205212646362
  (0, 4945)	0.11139882433235132
  (0, 3006)	0.5407901914737477
  (0, 1283)	0.13101191815158045
  (0, 2288)	0.09233971976255248
  (0, 1930)	0.07545078847642188
  (0, 3560)	0.09118873935403647
  (0, 1367)	0.059150363777104115
  (0, 1961)	0.05885037311736627
  (0, 1621)	0.07013151243777146
  (0, 4376)	0.041140506476506335
  (0, 4176)	0.16983202404305697
  (0, 3702)	0.032031441621952234
  (0, 4746)	0.2548741467648521
  (0, 3811)	0.041969346732185206
  (0, 4779)	0.11153195129508589
  (0, 1741)	0.035472422121786217
  (0, 4502)	0.07283552462449676
  (0, 3862)	0.16752611681444166
  (0, 1631)	0.0576217542234331
  (0, 1861)	0.06845824118743205
  (0, 3338)	0.061366791014583894
  (0, 3341)	0.08006388071492844
  (0, 3442)	0.07509506753428358
  :	:
  (49581, 1845)	0.053195171327882866
  (49581, 2768)	0.07015458025995226
  (49581, 4143)	0.06938758902402517
  (49581, 4900)	0.08908140849157115
  (49581, 1541)	0.14566504850620773
  (49581, 4499)	0.07783924982279847
  (49581, 442)	0.09309269295946308
  (49581, 4282)	0.09104756975317031
  (49581, 1956)	0.08340918168988351
  (49581, 2187)	0.11560648088044592
  (49581, 2217)	0.07902789826224896
  (49581, 4353)	0.14733034017324276
  (49581, 4637)	0.09640331143051332
  (49581, 3658)	0.07076991035190025
  (49581, 1974)	0.1064376369643931
  (49581, 535)	0.10424262350845194
  (49581, 1876)	0.11415751607759722
  (49581, 4464)	0.13279304150129592
  (49581, 4042)	0.16708729057669827
  (49581, 4745)	0.13265015940499897
  (49581, 345)	0.12182069649401307
  (49581, 2700)	0.14482608037545805
  (49581, 449)	0.11021024159247277
  (49581, 1764)	0.13074236543013942
  (49581, 3499)	0.1254410301678887

## Dataset & DataLoaders

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
X_train.shape

(39665, 5000)

In [33]:
X_test.shape

(9917, 5000)

In [34]:
import torch 
from torch.utils.data import TensorDataset, DataLoader

In [35]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [36]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)
test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [37]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

## Build our RNN

In [38]:
import torch.nn as nn
import torch.optim as optim

In [49]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()
        
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        #RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        #fully connected layer
        self.fc = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        #optional => shape(no. of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        #value1 - hidden state of all the timestamps => (batch, seqlen, hidden_size)
        #value2 - final hidden state of last timestamp

        out = self.fc(out[:, -1, :])
        return out

In [50]:
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

## Training the RNN

In [52]:
epochs = 10

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        xb = xb.unsqueeze(1) #add singleton direction
        
        outputs = model(xb) #(batch_size, 1)
        
        outputs = torch.sigmoid(outputs.squeeze()) #(batch_size,) => probability

        loss = criterion(outputs, yb)
        loss.backward() #back propagation
        optimizer.step() #weights update

        running_loss += loss.item()
        
    print(f"epoch {epoch+1}/{epochs}, loss = {running_loss / len(train_loader)}")

epoch 1/10, loss = 0.38102068809732315
epoch 2/10, loss = 0.26766715100215327
epoch 3/10, loss = 0.2521529726443752
epoch 4/10, loss = 0.24568450885914986
epoch 5/10, loss = 0.2420311411902789
epoch 6/10, loss = 0.23858428957962222
epoch 7/10, loss = 0.23684337759210217
epoch 8/10, loss = 0.23516037704483156
epoch 9/10, loss = 0.2337050641977018
epoch 10/10, loss = 0.23283086395071398

In [53]:
model.eval()

with torch.no_grad():
    correct_vals = 0
    total_vals = 0
    for xb, yb in test_loader:
        xb = xb.unsqueeze(1)

        outputs = model(xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        total_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()
    
    print(f"accracy = {correct_vals / total_vals * 100}")

accracy = 85.73157204799838